import type { User } from "@/types"

export const users: User[] = [
  {
    id: "emp-001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@gov.in",
    mobile: "9876543210",
    department: "Finance Ministry",
    employeeId: "EMP-2024-001",
    verificationStatus: "verified",
    idDocument: "Aadhaar Card",
    role: "employee",
  },
  {
    id: "emp-002",
    name: "Priya Sharma",
    email: "priya.sharma@gov.in",
    mobile: "9876543211",
    department: "Home Affairs",
    employeeId: "EMP-2024-002",
    verificationStatus: "verified",
    idDocument: "PAN Card",
    role: "employee",
  },
  {
    id: "emp-003",
    name: "Amit Patel",
    email: "amit.patel@gov.in",
    mobile: "9876543212",
    department: "Defence",
    employeeId: "EMP-2024-003",
    verificationStatus: "pending",
    idDocument: "Service ID",
    role: "employee",
  },
  {
    id: "emp-004",
    name: "Sneha Reddy",
    email: "sneha.reddy@gov.in",
    mobile: "9876543213",
    department: "Railways",
    employeeId: "EMP-2024-004",
    verificationStatus: "verified",
    idDocument: "Aadhaar Card",
    role: "employee",
  },
  {
    id: "emp-005",
    name: "Vikram Singh",
    email: "vikram.singh@gov.in",
    mobile: "9876543214",
    department: "External Affairs",
    employeeId: "EMP-2024-005",
    verificationStatus: "rejected",
    idDocument: "Passport",
    role: "employee",
  },
  {
    id: "emp-demo",
    name: "Demo Employee",
    email: "demo.employee@gov.in",
    mobile: "9999999999",
    department: "IT Ministry",
    employeeId: "EMP-2024-DEMO",
    verificationStatus: "verified",
    idDocument: "Aadhaar Card",
    role: "employee",
  },
]

export const adminUser = {
  id: "admin-001",
  name: "Super Admin",
  email: "admin@govguesthouse.in",
  username: "admin",
  password: "admin123",
  role: "admin" as const,
}
